import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#d2d6db",
        outline: "#6b7380",
        "on-primary-fixed": "#001e31",
        "on-primary-container": "#004b72",
        "on-background": "#1a1d23",
        "surface-variant": "#edf0f3",
        "on-primary": "#ffffff",
        "surface-container-low": "#f5f7f9",
        "surface-bright": "#ffffff",
        "primary-fixed-dim": "#91cdff",
        secondary: "#964900",
        "primary-fixed": "#cce5ff",
        "on-surface": "#1a1d23",
        "secondary-fixed-dim": "#ffb786",
        "secondary-fixed": "#ffdcc6",
        primary: "#006496",
        "on-secondary-fixed-variant": "#723600",
        "tertiary-fixed": "#d0f05e",
        "primary-container": "#64bdff",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#f4f5f7",
        background: "#ffffff",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#a3c134",
        "on-surface-variant": "#4a5060",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#171e00",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#3e4c00",
        tertiary: "#536600",
        "inverse-primary": "#91cdff",
        surface: "#ffffff",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#6d3400",
        "inverse-surface": "#2d3038",
        "secondary-container": "#ff9648",
        "surface-container-highest": "#dde1e6",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#b4d345",
        "surface-container-high": "#e6e9ed",
        "surface-container": "#edf0f3",
        error: "#ba1a1a",
        "on-tertiary-fixed-variant": "#3e4c00",
        "on-primary-fixed-variant": "#004b72",
        "outline-variant": "#c5cad3",
        "on-secondary-fixed": "#311300",
        "surface-tint": "#006496",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
